- hosts: all
  user: root
  tasks:
    - yum_repository:
        name: yarn
        description: Yarn Repository
        baseurl: https://dl.yarnpkg.com/rpm/
        gpgcheck: yes
        gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg
    - yum:
        name: 'yarn'
    - npm:
        name: forever
        global: yes
    - copy:
        src: ./{{ item }}
        dest: /work/
      with_items:
        - src
        - client
        - package.json
        - yarn.lock
        - tsconfig.json
        - gulpfile.ts
    - yarn:
        path: /work
        state: latest
    - command: yarn build
      args:
        chdir: /work
    - file:
        path: /shh
        state: directory
    - copy:
        src: ./{{ item }}
        dest: /shh/
      with_items:
        - package.json
        - yarn.lock
        - config.json
        - ps4-wake.credentials.json
        - forever.json
    - yarn:
        path: /shh
        state: latest
        production: yes
    - command: cp -fRT /work/app /shh/app
    - file:
        path: /work
        state: absent
    - firewalld:
        port: 3000/{{ item }}
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - tcp
        - udp
    - cron:
        name: SmartHomeHub
        special_time: reboot
        job: NODE_ENV=production forever start /shh/forever.json
    - command: forever list
      register: result
    - command: forever start /shh/forever.json
      environment:
        NODE_ENV: production
      when: result.stdout.find('/shh/app/bin/www.js') == -1
      become: ture
      become_user: nobody
    - command: forever restart /shh/app/bin/www.js
      when: result.stdout.find('/shh/app/bin/www.js') != -1
      become: ture
      become_user: nobody
