- hosts: all
  user: root
  tasks:
    - name: Install Node Repo
      shell: curl --silent --location https://rpm.nodesource.com/setup_10.x | bash -
    - yum_repository:
        name: yarn
        description: Yarn Repository
        baseurl: https://dl.yarnpkg.com/rpm/
        gpgcheck: yes
        gpgkey: https://dl.yarnpkg.com/rpm/pubkey.gpg
    - yum:
        name: 'yarn'
    - npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - forever
        - lerna
    - copy:
        src: ./{{ item }}
        dest: /work/
      with_items:
        - packages
        - lerna.json
        - package.json
        - postcss.config.js
        - yarn.lock
    - yarn:
        path: /work
    - command: lerna run build
      args:
        chdir: /work
    - file:
        path: /shh/app
        state: directory
    - copy:
        remote_src: yes
        src: /work/dist/
        dest: /shh/app/
    - copy:
        src: "{{ item }}"
        dest: /shh/
      with_items:
        - forever.json
        - packages/server/
        - yarn.lock
    - yarn:
        path: /shh
        production: yes
    - file:
        path: /work
        state: absent
    - firewalld:
        port: 3000/{{ item }}
        permanent: true
        immediate: true
        state: enabled
      with_items:
        - tcp
        - udp
    - cron:
        name: SmartHomeHub
        special_time: reboot
        job: NODE_ENV=production forever start /shh/forever.json
    - command: forever list
      register: result
    - command: forever start /shh/forever.json
      environment:
        NODE_ENV: production
      when: result.stdout.find('/shh/app/bin/www.js') == -1
      become: ture
      become_user: nobody
    - command: forever restart /shh/app/bin/www.js
      when: result.stdout.find('/shh/app/bin/www.js') != -1
      become: ture
      become_user: nobody
